

services:
  web:
    build: .
    container_name: student_tracker_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////data/app.db
      - SECRET_KEY=PVLEisUey6x4
      - ADMIN_USER=master
      - ADMIN_PASS=Huang923800
    volumes:
      - app_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
volumes:
  app_data:
